import PiQuasi.SafetyCriticalLeakageGate

#print axioms PiQuasi.open_boundary_not_exactly_no_escape
#print axioms PiQuasi.open_boundary_rejected_by_exact_safety_policy
#print axioms PiQuasi.spatial_pi_operational_model_not_exactly_no_escape
#print axioms PiQuasi.spatial_pi_operational_model_rejected_by_exact_safety_policy
#print axioms PiQuasi.potentially_unbounded_delay_does_not_restore_exact_containment
