import ClassicalEuclideanTraversalStep

#print axioms PiQuasiClassicalBridge.gregory_correction_nonzero
#print axioms PiQuasiClassicalBridge.traversal_angle_step_nonzero
#print axioms PiQuasiClassicalBridge.abs_gregory_correction
#print axioms PiQuasiClassicalBridge.abs_traversal_angle_step
#print axioms PiQuasiClassicalBridge.traversal_angle_step_abs_le_eight_thirds
#print axioms PiQuasiClassicalBridge.traversal_angle_step_abs_lt_two_pi
#print axioms PiQuasiClassicalBridge.radius_circle_point_is_euclidean
#print axioms PiQuasiClassicalBridge.radius_circle_point_changes_under_gregory_step
#print axioms PiQuasiClassicalBridge.circumference_correction_nonzero
#print axioms PiQuasiClassicalBridge.circumference_correction_over_radius
#print axioms PiQuasiClassicalBridge.circle_traversal_by_length_is_on_circle
#print axioms PiQuasiClassicalBridge.euclidean_endpoint_changes_under_every_gregory_circumference_correction
#print axioms PiQuasiClassicalBridge.classical_euclidean_traversal_step_closure
